services:
  container:
    build: .
    container_name: gpt-discord-bot
    network_mode: host
    restart: unless-stopped
    volumes:
    # Windows runtime
      - ./:/app:ro
    # Linux runtime
    #  - /opt/gpt-discord-bot/:/app:ro
